Repository paritytech/finality-grandpa, pull requests merged in 2018-12, with the labels that each got.

#33 Expose commit validation
  Cargo.toml
  src/lib.rs
  src/voter.rs
Labels: A8-looksgood

#35 update to 2018 edition
  Cargo.toml
  src/bridge_state.rs
  src/lib.rs
  src/round.rs
  src/testing.rs
  src/vote_graph.rs
  src/voter.rs
Labels: A2-insubstantial

#38 adjust base in vote_graph
  src/vote_graph.rs
Labels: A0-pleasereview
