Repository paritytech/finality-grandpa, pull requests merged in 2019-01, with the labels that each got.

#36 count equivocations on all votes
  src/bitfield.rs
  src/lib.rs
  src/round.rs
  src/voter.rs
Labels: A8-looksgood

#39 Validate commits with Round and generate commits under new equivocation rules
  src/lib.rs
  src/round.rs
  src/voter.rs
Labels: A0-pleasereview

#43 Update Parking lot dependency
  Cargo.toml
Labels: A2-insubstantial
