Repository paritytech/finality-grandpa, pull requests merged in 2019-04, with the labels that each got.

#58 Expose round votes through Environment
  src/round.rs
  src/testing.rs
  src/voter/mod.rs
  src/voter/voting_round.rs
Labels: A8-looksgood

#56 Add callbacks to commit
  src/lib.rs
  src/round.rs
  src/testing.rs
  src/voter/mod.rs
  src/voter/voter_state.rs
  src/voter/voting_round.rs
Labels: A0-pleasereview

#60 Grant access to voters
  src/voter_set.rs
Labels: A5-grumble
