Repository paritytech/finality-grandpa, pull requests merged in 2020-01, with the labels that each got.

#101 Tweak fuzzing and a fix for `VoteGraph::find_ancestor`.
  fuzz_corpus/crash-499bf756959c90958d05c669b77b4a6f85e4fbf5
  src/fuzz_helpers.rs
  src/round.rs
  src/vote_graph.rs
Labels: A0-pleasereview

#100 Upgrade to stable futures (#2).
  Cargo.toml
  src/bridge_state.rs
  src/testing.rs
  src/voter/mod.rs
  src/voter/past_rounds.rs
  src/voter/voting_round.rs
Labels: A1-onice, A8-looksgood

#104 Changes needed for substrate#4612
  Cargo.toml
  src/fuzz_helpers.rs
  src/lib.rs
  src/voter/mod.rs
Labels: A3-inprogress, A6-mustntgrumble

#93 VoterSet and Bitfield Refactoring
  Cargo.toml
  src/bitfield.rs
  src/fuzz_helpers.rs
  src/lib.rs
  src/round.rs
  src/round/context.rs
  src/vote_graph.rs
  src/voter/mod.rs
  src/voter/voting_round.rs
  src/voter_set.rs
  src/weights.rs
Labels: A0-pleasereview

#106 Fix sending of finality notification
  src/lib.rs
  src/round.rs
  src/voter/voting_round.rs
Labels: A0-pleasereview, M4-core

#105 Backport #101: fix find_ancestor.
  src/round.rs
  src/vote_graph.rs
Labels: A0-pleasereview, A8-backport

#107 Backport #106: Fix sending of finality notification
  src/bitfield.rs
  src/lib.rs
  src/round.rs
  src/voter/voting_round.rs
  src/voter_set.rs
Labels: A0-pleasereview, A8-backport
